apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: ./../prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system