apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
data:
  backup-script.sh: |
    #!/bin/bash
    mongodump --uri="mongodb://mongo:27017" --out=/mnt/backup/mongo
    azcopy cp "/mnt/backup/mongo" "https://$azurestorageaccountname.blob.core.windows.net/$containername/mongo-backup" --recursive