apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "10 * * * *"  # Runs every 10 min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mcr.microsoft.com/azure-cli:latest
              command: ["/bin/bash", "-c"]
              args: ["chmod +x /backup/backup.sh && /backup/backup.sh"]
              volumeMounts:
                - name: mongodb-storage
                  mountPath: /data/db
                - name: backup-script
                  mountPath: /backup
              env:
                - name: AZURE_STORAGE_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: azurestorageaccountname
                      key: azurestorageaccountname
                - name: AZURE_STORAGE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: azurestorageaccountkey
                      key: azurestorageaccountkey
                - name: AZURE_CONTAINER
                  valueFrom:
                    secretKeyRef:
                      name: containername
                      key: containername
          restartPolicy: OnFailure
          volumes:
            - name: mongodb-storage
              persistentVolumeClaim:
                claimName: mongodb-pvc
            - name: backup-script
              configMap:
                name: backup-script-config