apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 16 * * *"  # Exécuter tous les jours à 16h
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mcr.microsoft.com/mirror/docker/library/mongo:4.2
            command: ["/bin/bash", "-c", "/path/to/backup_script.sh"]
            env:
            - name: MONGO_HOST
              value: "your-mongodb-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "your-database"
            volumeMounts:
            - name: azure-blob-storage
              mountPath: /mnt/backup
          restartPolicy: OnFailure
          volumes:
          - name: azure-blob-storage
            persistentVolumeClaim:
              claimName: azure-blob-pvc
