apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "10 * * * *"  # Runs every 10 min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mcr.microsoft.com/azure-cli
              command: ["/bin/bash", "-c"]
              args: ["./backup.sh"]
              volumeMounts:
                - name: mongodb-storage
                  mountPath: /data/db
                - name: backup-script
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: mongodb-storage
              persistentVolumeClaim:
                claimName: mongodb-pvc
            - name: backup-script
              configMap:
                name: backup-script-config