apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "10 * * * *" # Runs every 10 min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-backup
              image: appropriate/curl
              command: ["/bin/sh", "-c"]
              args: ["/scripts/backup-mongodb.sh"]
              volumeMounts:
                - name: backup-script
                  mountPath: /scripts
              env:
                - name: AZURE_STORAGE_ACCOUNT
                  value: $azurestorageaccountname
                - name: AZURE_CONTAINER
                  value: $containername
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: backup-script