# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   azureDisk:
#     diskName: mongodb-disk
#     diskURI: https://$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$AZURE_CONTAINER/$BACKUP_NAME
#   storageClassName: azure-disk
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: azure-disk

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    diskName: mongodb-disk
    diskURI: /subscriptions/$subid/resourcegroups/k8s-terraks/providers/microsoft.compute/disks/{disk-id}
    cachingMode: ReadWrite
    fsType: ext4
    kind: Managed

