# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongodb-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   azureDisk:
#     diskName: mongodb-disk
#     diskURI: https://$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$AZURE_CONTAINER/$BACKUP_NAME
#   storageClassName: azure-disk
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: azure-disk

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    diskName: mongodb-disk
    diskURI: "https://$azurestorageaccountname.blob.core.windows.net/$containername/mongodb-disk.vhd"
    kind: Managed
    fsType: ext4