apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-blob
  azureFile:
    secretName: azure-secret
    shareName: azure-blob-pvc
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-blob
  resources:
    requests:
      storage: 10Gi